a=input('enter  text to write to the file')
file1=open('output.txt','w')
file1.write(a)
file1.close()
print('Data successfully witten to output.txt file ')
print()
b=input('enter additional text to append to the file')
file1=open('output.txt','a')
file1.write(b)
file1.close()
print('Data successfully appended')
print()
print('final context of the file')
file1=open('output.txt','r')
print(file1.read())
file1.close()
